general:
  world_blacklist: [] # enter the name of the world in which you want to disable the restriction

  # enter the name of enabled the restriction here
  # all: creative, pickup, drop, usage, crafting, smelting, placement
  restrictions:
    - creative
    - pickup
    - drop
    - usage
    - crafting
    - smelting
    - placement

command:
  reload: '&cConfig and RestrictedItems reload complete!'
  help: '/<label> reload'
  unknownCommand: '&cUnknown command! for help do:&7 /<label>'
